### ISSUE TITLE
Ability to sync specific email account

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#104]
There is ability to sync only specific folder, using this command
`./sync/sync --folder FOLDERNAME`

It would be great to be able to sync only specific account this way.
`./sync/sync --email somemail@somehost.com`

and account and folder like this
`./sync/sync --email somemail@somehost.com --folder FOLDERNAME`

**Comment by mikegioia** [comment]
I think this is a great idea

**Comment by mikegioia** [comment]
Resolved via #108
