### ISSUE TITLE
Sync with Exchange in cloud (outlook.office365.com) does not work

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#105]
**Describe the bug**
When trying to sync all folders for account in outlook.office365.com messages does not synced. In interactive mode there are errors like this:
```
[11-Mar-20 07:53:58] DEBUG: Downloading messages in Notes
[11-Mar-20 07:53:58] DEBUG: Found 0 messages, none are new
[11-Mar-20 07:53:58] DEBUG: No messages to delete in Notes
[11-Mar-20 07:53:58] ERROR: cannot read - connection closed?
```

**To Reproduce**
1. Add account from outlook.office365.com
```
imap_server: outlook.office365.com
imap_port: 993
smtp_server: smtp.office365.com
smtp_port: 587
username: somemail@domain.com
password: somepassword
```
2. Run ./sync/sync
3. See errors in console

**Expected behavior**
Messages should be synced.

**Server:**
 - OS: Ubuntu 16.04

**Cause of error**
Some folders cause libremail sync hangs.

**Possible solution**

_Folders, breaking sync process:_
This folders should be exclude from sync.
- Archive
- Calendar
- Calendar/Birthdays
- Calendar/United States holidays
- Contacts
- Conversation History
- Junk Email
- Outbox
- RSS Feeds
- Tasks
- Notes

_Folders, can be synced_
- Deleted Items
- Drafts
- INBOX
- Journal
- Sent Items
- Trash

**Comment by mikegioia** [comment]
I'm going to track this over at #120

**Comment by rinshadka** [comment]
Hello,

Just curious to know whether this application supports new authentication requirements needed for connecting to organization owned azure o365 accounts.

I have worked on steampipe IMAP plugin and unfortunately they wont support -[ **issue**](https://github.com/turbot/steampipe-plugin-imap/issues/23#issuecomment-1658473050) 

We got this connected in EmailEngine software using the Oauth2 application - [**reference**](https://docs.emailengine.app/setting-up-oauth2-with-outlook/)


Thanks.
