### ISSUE TITLE
Store folders realtime sync status

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#107]
**Describe the bug**
Now there is no way to know is folder syncing just now.

**Possible solution**
We need to save folder syncing state in database. 
I suggest to add info to the folder table sync info, because in the future, several sync may be used.

- sync_status - actual real-time sync status
- sync_host - last host, that synced folder / current syncing host
- sync_pid- last process id, that synced folder / current syncing process id
- synced_at - last sync timestamp

**Sync status**

1. NOT_SYNCED
2. SYNCING
3. SYNCING_NEED_RESYNC
4. SYNCED_NEED_RESYNC
5. SYNCED
6. ERROR

**NOT_SYNCED**
Initial state, when folder just added to database and syncing process has never processed.

**SYNCING**
This folder is syncing now.

**SYNCING_NEED_RESYNC**
This folder is syncing now, and we received one or more request for resync after syncing process started. Example: syncing process started and user delete / change flag of message, which already synced. We can not miss this event and resyncing needed.

**SYNCED_NEED_RESYNC**
This folder is just synced, another folder of the same account is syncing now.
That means, that sync is running now for this account.
After account sync is complete we need to resync this folder, because watcher tell us, that folder is changed.

**SYNCED**
Sync process completed and there is no new events received from imap server ("mail" / "update" / "purge").

**ERROR**
There was some error, during sync process.

**Comment by mikegioia** [comment]
@netandreus I very much appreciate the # of issues and the pull requests :D I'm just going to temporarily close this one until they're ready to be worked on or have some more info. I'm using this issues list day to day until I get version 1 of the webmail out.

**Comment by mikegioia** [comment]
I think the current folder being synced might be stored already in a table, but I have to check and get back to you.

**Comment by mikegioia** [comment]
No we're not storing it. We could probably set up a flag on the folders table to store a "status" for when the folder is being processed. The Sync class currently calls `$this->stats->setActiveFolder()` to send a message to the admin webpage.

We might be able to set the status flag somewhere in the Stats class' `setActiveFolder()` and `unsetActiveFolder()`.

**Comment by netandreus** [comment]
Ok, @mikegioia. Thanks for information! I think I can realize storing status in database. I will send pull request to you, if you do not mind.

**Comment by netandreus** [comment]
@mikegioia pick out my work with this task to separate branch and pull request https://github.com/mikegioia/libremail/pull/119

**Comment by mikegioia** [comment]
The `Stats` class stores this information in the `meta` table, whenever the active folder is updated or whenever the sync is started or finished. I think if we tried to store the status on the folders table, we run the risk that if the sync halts, the status could be stuck or wrong.
