### ISSUE TITLE
Multiple definitian exists for class Folder / Account / Message

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#111]
**Bug description**
There are number of projects in one (this) repository:
- webmail
- sync

Both of this projects has the same namespace = "App". And same classes: "Folder", "Account", "Message". So, my IDE (PHPSotrm) emit error "Multiple definitian exists for class Folder / Account / Message". After this line of code:

```use App\Model\Folder as FolderModel;```

IDE can't determine which one of this
```
./webmail/src/Model/FolderModel.php
./sync/src/Model/FolderModel.php
```
I will use. And unfortunately autocomplete does not work.

**Possible solution**
Create separete root namespace for ever of this projects.

**Comment by mikegioia** [comment]
@netandreus They're two different projects with two different composer files. I unfortunately don't think this is a reasonable change to make. It sounds like an IDE problem.
