### ISSUE TITLE
SQL error in Message->getThreads()

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#112]
**Describe the bug**
After running webmail there is an error on main page.

**To Reproduce**
1. Run ./sync/sync
2. Run ./sync/libremail
3. Go to webmail web page

**Expected behavior**
Web interface is running

**Screenshots**
![getThreadsError](https://user-images.githubusercontent.com/313477/76731947-965e1380-676f-11ea-9361-7b7b01627835.PNG)

**Comment by netandreus** [comment]
@mikegioia hello! This pull request https://github.com/mikegioia/libremail/pull/113 fixes just this bug

**Comment by mikegioia** [comment]
Thank you @netandreus I actually have this fixed in the branch `reply-final`, but I appreciate it.
