### ISSUE TITLE
Outbox table empty

### ISSUE THREAD

**Issue by mixian** [mikegioia/libremail#129]
Hi Mike,
i noticed that the database outbox table is always empty. From the documentation I cannot understand if it is a configuration problem.

I realized because I wanted to view only the sent mail and from the "messages" table it is more complex than having them all in the "outbox".

How can I solve it?

Thanks for everything.

**Comment by mikegioia** [comment]
Hi @mixian -- The outbox table is used with the "webmail" project in the root folder. That's actively under development right now and it's a full-featured webmail client to send/receive emails and display all of your folders, etc. It does NOT send emails correctly right now and I would not use it to send anything, but hopefully in about 2-3 weeks it should be ready for that. It does display messages, threads, and mailboxes though.

I'm going to close this out as it's not specifically a bug report, but by all means please feel 100% open to emailing me any questions at all, about anything. I would kindly prefer to keep the issues just as bugs for now.
