### ISSUE TITLE
When I run the program, there is such an error

### ISSUE THREAD

**Issue by lijiaxin06** [mikegioia/libremail#133]
NOTICE: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF5\xA3\xA8\xB1\xDE\xB9...' for column `libremail`.`messages`.`raw_content` at row 1

**Comment by mikegioia** [comment]
Greetings @lijiaxin06 -- This error is interesting, I think it has to do with the database table string encoding / character set. Do you mind please checking to see what the character set is for your table `libremail.messages` and then for the field `libremail.messages.raw_content`?

I think this a bug in the code when it saves the value `raw_content` (and possibly any other value). The field's character set should be `utf8mb4_unicode_ci` and my hunch is that Libremail should either use `utf8_encode` before saving the field to SQL, or we should strip those non-readable unicode characters from the `raw_content` before saving it.

**Comment by mikegioia** [comment]
@lijiaxin06 Also, if you are able to try this -- please edit [`sync/src/Traits/Model.php` on line 150](https://github.com/mikegioia/libremail/blob/master/sync/src/Traits/Model.php#L150). That is probably not working properly to encode the string before saving. I would try editing it to:

```
$data[$key] = utf8_encode($data[$key]);
```

and checking to see if that works instead. If it doesn't, try removing the `@` before `iconv` and see if that is throwing any error messages.
