### ISSUE TITLE
Fn is keyword in PHP 7.4 and throws a fatal error

### ISSUE THREAD

**Issue by mafa1993** [mikegioia/libremail#134]
**Describe the bug**
php7.4  Fn is keyword，Fatal error

**To Reproduce**
1. Go to '...'  /home/www/webmail/libremail-master/sync/src/Functions.php
2. Click on '....' line3 
3. Scroll down to '.... '  line3

**Expected behavior**
PHP Parse error:  syntax error, unexpected 'Fn' (T_FN), expecting '{' in /home/www/webmail/libremail-master/sync/src/Functions.php on line 3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu  16.04
 - Browser chrome 84
 - Version 

**Additional context**
php7.4   exec install error， change libremail-master/sync/src/Functions.php namespace can fix it

**Comment by mikegioia** [comment]
Thank you @mafa1993. I'm unfamiliar with this error, I actually have not tested this at all in PHP 7.4 Does this mean the namespace "Fn" is not valid? If that's the case, that might be a larger-scale update for me. Those Fn/xyz() functions are used pretty much everywhere unfortunately.

**Comment by mafa1993** [comment]
change namespce Fn to another will  solved this problem

**Comment by mikegioia** [comment]
Related to #139, working on this one soon

**Comment by mikegioia** [comment]
Completed in #141
