### ISSUE TITLE
Add support for JMAP (JSON Meta Application Protocol), as an alternative to IMAP + SMTP

### ISSUE THREAD

**Issue by marclaporte** [mikegioia/libremail#92]
"JMAP is intended to be a new standard for email clients to connect to mail stores. It therefore intends to primarily replace IMAP + SMTP submission. It is also designed to be more generic such that it can be extended with contacts, calendars in the future (replacing CardDAV/CalDAV). It does not replace MTA-to-MTA SMTP transmission."

Please see: http://jmap.io/

**Comment by mikegioia** [comment]
Thanks @marclaporte, this is definitely something I will add in the long-term. I'm closing it out now as it'll be at least a year before I can get to it.

**Comment by marclaporte** [comment]
I suggest adding a "long term" tag instead of closing. It signals intent without commitment and can perhaps attract contributors.

FYI: https://tools.ietf.org/html/rfc8620
